/* DROP TABLE `Aluno`; */
/* ALTER TABLE `Turma`
	ADD COLUMN `Tipo` VARCHAR(15) NOT NULL DEFAULT 'MÉDIO';
 
 ALTER TABLE `Turma`
	DROP COLUMN `Tipo`
 */
 ALTER TABLE `Turma`
	ADD COLUMN `Tipo` VARCHAR(15) NOT NULL DEFAULT 'MÉDIO';