/* ALTER TABLE `Aluno`
	MODIFY COLUMN `ESTADO` CHAR(2) NOT NULL; */
/*
ALTER TABLE `Aluno`
	MODIFY COLUMN `CPF` VARCHAR(11) NOT NULL;
    */
ALTER TABLE `Aluno`
	CHANGE COLUMN `Estado` `UF` CHAR(2) NOT NULL;