Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/11/2022
Var
ant2,ant1,prox,n,i: inteiro


Inicio
escreval("Digite um numero: ")
leia(n)
repita

ant2:=i+(n-2)
ant1:=i+(n-1)
prox:=i+(n+1)
escreval(ant2,ant1,prox)

i:=i+1
 ate (i=n)

Fimalgoritmo