Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/11/2022
Var

  num,Ix:inteiro

Inicio
   escreval("Digite um numero: ")
   leia(num)
para Ix de 1 ate 10 passo 1 faca
      escreval(num,"x",Ix," =",num*Ix)
      Ix:=Ix+1
         fimpara
   escreval("Fim do programa")


Fimalgoritmo