Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/11/2022
Var
   num,Ix:inteiro


Inicio
   escreval("Digite um numero: ")
   leia(num)
   enquanto (Ix<10) faca
      escreval(num,"x",Ix," =",num*Ix)
      Ix:=Ix+1
   fimenquanto
   escreval("Fim do programa")
Fimalgoritmo